name: HalloweenEffects
version: ${project.version}
main: me.numin.halloweeneffects.HalloweenEffects
api-version: 1.16
authors: [Numin]
description: Adds a few halloween cosmetics!

commands:
  he:
    usage: /<command>
    aliases: halloweeneffects
    description: Basic help list
  he set:
    usage: /<command>
    aliases: he s
    description: Activates an effect.
  he remove:
    usage: /<command>
    aliases: he r
    descriptions: Removes an effect.
  he list:
    usage: /<command>
    aliases: he l
    descriptions: Lists valid effects.

permissions:
  halloween.command.op:
    default: op
  halloween.trail.spookybats:
    default: true
  halloween.trail.pumpkinhead:
    default: true
